version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/workdir
    steps:
      - checkout
      - restore_cache:
          key: slf4j-javame-{{ checksum "pom.xml" }}
      - run: mvn clean package -DskipTests dependency:go-offline --settings .circleci/.m2/settings.xml --show-version
      - save_cache:
          paths:
            - ~/.m2
          key: slf4j-javame-{{ checksum "pom.xml" }}
      - run: mvn install --fail-at-end --offline --settings .circleci/.m2/settings.xml
      - store_test_results:
          path: slf4j-api/target/surefire-reports
      - store_test_results:
          path: slf4j-simple/target/surefire-reports
      - persist_to_workspace:
          root: ~/workdir
          paths:
            - .
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: slf4j-javame-{{ checksum "pom.xml" }}
      - run: mvn deploy -DskipTests --settings .circleci/.m2/settings.xml
  release:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: slf4j-javame-{{ checksum "pom.xml" }}
      - run: mvn release:clean initialize release:prepare release:perform --batch-mode -DskipTests --offline --settings .circleci/.m2/settings.xml
workflows:
  version: 2
  build-and-deploy-snapshot-and-wait-release-approval:
    jobs:
      - build:
          context: ArtifactRepository
      - deploy:
          context: ArtifactRepository
          requires:
            - build
      - wait-release-approval:
          type: approval # A job that will require manual approval in the CircleCI web application.
          requires:
            - deploy
          filters:
            branches:
              only: master
      - release:
          context: ArtifactRepository
          requires:
            - wait-release-approval
          filters:
            branches:
              only: master
