version: 2
jobs:
  build:
    docker: 
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
        key: slf4j-javame-{{ checksum "pom.xml" }}
      - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
      - save_cache:
        paths:
          - ~/.m2
        key: slf4j-javame-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
        path: target/surefire-reports
